# Workflow to keep action docs up to date
name: "Sync docs with action.yml"
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  update:
    runs-on: [self-hosted, research]
    steps:
      - uses: actions/checkout@v2.3.4

      - uses: npalm/action-docs-action@v1.1.0

      - name: Update readme in the repository
        uses: stefanzweifel/git-auto-commit-action@v4.11.0
        with:
          commit_message: "chore(ci): Updating readme"
          file_pattern: README.md